services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"

  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  pgdata:
